# Generated by Django 5.0.7 on 2024-08-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Price', models.IntegerField()),
                ('Type', models.CharField(choices=[('plastic', 'plastic'), ('wooden', 'wooden'), ('steel', 'steel')], max_length=25)),
                ('Details', models.TextField()),
            ],
        ),
    ]
